# Generated by Django 4.0.4 on 2022-05-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('record_book_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=80)),
                ('telephone', models.CharField(max_length=30)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('group_code', models.ForeignKey(db_column='Group Code', on_delete=django.db.models.deletion.DO_NOTHING, to='univerce.groups')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
