# Generated by Django 4.0.4 on 2022-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerce', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
