# Generated by Django 4.0.4 on 2022-05-06 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univerce', '0003_alter_students_status_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_math_hours', models.SmallIntegerField(blank=True, null=True)),
                ('number_of_hours_of_physical_education', models.SmallIntegerField(blank=True, null=True)),
                ('number_of_programming_hours', models.SmallIntegerField(blank=True, null=True)),
                ('number_of_physics_hours', models.SmallIntegerField(blank=True, null=True)),
                ('number_of_chemistry_hours', models.SmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='groups',
            name='kod_plana',
        ),
        migrations.AlterField(
            model_name='students',
            name='record_book_number',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='curriculum_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='univerce.curriculum'),
        ),
    ]
