# Generated by Django 4.0.4 on 2022-05-07 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerce', '0004_curriculum_remove_groups_kod_plana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='number_of_chemistry_hours',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='number_of_hours_of_physical_education',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='number_of_math_hours',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='number_of_physics_hours',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='number_of_programming_hours',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='status_date',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_four',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_four_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_one_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_three',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_three_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_two',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_two_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
