# Generated by Django 4.0.4 on 2022-05-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerce', '0005_remove_curriculum_number_of_chemistry_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='status',
            field=models.CharField(choices=[('AP', 'approved'), ('UC', 'under consideration')], max_length=50),
        ),
    ]
