# Generated by Django 4.0.4 on 2022-05-08 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerce', '0007_remove_curriculum_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='subject_one_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_two',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_two_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_three',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_three_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_four',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subject_four_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='status',
            field=models.CharField(default='approved', max_length=50),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
