# Generated by Django 4.0.4 on 2022-05-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerce', '0008_curriculum_create_date_curriculum_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
