# Generated by Django 4.0.4 on 2022-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univerce', '0010_alter_groups_status_alter_groups_status_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(blank=True, default='enlisted', max_length=50, null=True),
        ),
    ]
