# Generated by Django 4.0.4 on 2022-05-09 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('univerce', '0011_alter_students_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
